model_list:
  - model_name: __MODEL_ID__
    litellm_params:
      model: __MODEL_ID__
#      api_key: os.environ/OPENAI_API_KEY

guardrails:
  - guardrail_name: "inject-tools"
    litellm_params:
      guardrail: inject_tools.InjectToolsGuardrail
      mode: "pre_call"
      default_on: true